; TEST 0009 - BEDBOX PLATFORMIO.INI

[env:bedbox]
board = esp32-wroom-32
platform = espressif32@6.7.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
  arduino-esp32/ESP32 @ ^2.0.14
